# See https://docs.travis-ci.com/user/languages/r/
language: r

cache:
    packages: yes

script:
    - |
        Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: false
    local-dir: docs
    target_branch: gh-pages
    verbose: true
    fqdn: pghandbook.psy.plymouth.ac.uk

warnings_are_errors: false
