# See https://docs.travis-ci.com/user/languages/r/
dist: trusty
language: r
cache:
    packages: yes

latex: true
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

script:
    - |
    Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
    Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'

# See https://docs.travis-ci.com/user/deployment/pages/
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local-dir: docs/
    verbose: true
