## Academic dishonesty

\index{Academic dishonesty}

\index{Plagiarism}

Academic dishonesty includes plagiarism, collusion, cheating in exams and fabricating data. These practices and others related to dishonesty probably constitute the dirtiest words in academia, and they are quite properly punished severely where they are detected and proved. 

It is your job to familiarise yourself with the rules on plagiarism and academic dishonesty. Ignorance of the rules and expectations is not an excuse.


### University rules on AD

The University has very strict regulations about academic dishonesty. You will need to know what counts as academic dishonesty according to the university regulations and make sure you avoid committing any action which could be construed as dishonest.

Below is a list of practices which the University has identified as common instances of dishonesty.
(these examples are not necessarily exhaustive).

- Obtaining or attempting to obtain access to an unseen examination or test paper prior to the start
of the examination/test.

- The introduction or use in an examination/test of any books, notes, paper or devices of any kind other
than those specifically permitted in the rubric of the paper.

- Failing to comply with the instructions of an invigilator or examiner, or with the printed
instructions for candidates.

- Removing from an examination or test any script, paper, or other official stationery (whether or not
completed) unless specifically authorised by an invigilator or
examiner.

- Being party to any arrangement whereby a person other than the candidate fraudulently
represents, or intends to represent, the candidate in an examination or
test (personation).

- Communicating, or attempting to communicate with another student or with any third party other than
the invigilator/examiner during an examination or test.

- Use of crib sheets, revision notes etc at any time during an examination or test.

- Copying or attempting to copy the work of another student, whether by overlooking his/her work, asking
him/her for information, or by any other means.

- The submission for assessment of material (written, computer-generated, visual or oral) originally
produced by another person or persons, without indicating that the
material is not original, such that the work could be assumed to be the
student’s own.

- The unauthorised use of the work of another student (whether by taking a hard copy without
permission or through access to an electronic copy).

- The representation of work produced in collaboration with another person or persons as the work of
a single candidate.

- The inclusion in a piece of assessed work (other than an examination or in-class/end-module test) of
material which is identical or substantially similar to material which
has already been submitted for any other assessment within the
University.

- Making false declarations in an attempt to obtain special examination arrangements or special
consideration (e.g. of extenuating circumstances).

- The presentation of data in laboratory work, projects etc based on work purporting to have been
carried out by the student but which has been invented, copied, altered
or otherwise falsified.

- Attempting to persuade another member of the University (student, staff, or invigilator) to participate in any way in actions which would be in breach of this Regulation.

- Being party to any arrangement which would constitute a breach of this Regulation.






### Plagiarism

Plagiarism is one of the commonest forms of academic dishonesty; it isessentially copying or closely paraphrasing the work of another personwithout clearly indicating what has been copied or the source of thecopying. With the ready availability of the internet and the increasingaccess to on-line resources, it has become ever easier to commitplagiarism. The counter point to this trend is that with moresophisticated computer programmes and internet search engines, it isactually becoming more easy to detect plagiarism.


As well as cases where an individual student has intentionally set out to deceive the marker, it is not uncommon for students to commit some form of plagiarism but be unaware that they have committed an offence. In these circumstances, the most common mistakes are for students to:


Paraphrase the original source too closely
:	Paraphrase the original source too closely by changing the grammar or individual words of the original only slightly. Even though the student’s work is not a direct
quote it is still copying the ideas and expression of those ideas too closely.

	Solution: make sure you paraphrase key ideas from a source entirely in your own words.



Using notes directly
:	Making notes from a source (journal or book) which is a copy the original and then forgetting that your notes are a copy. When you come to write your assessment what you have in your notes sounds good so you use that material in your essay. However what you have put into your essay is a direct quote or a close paraphrase of the original. Even though the student may claim that they did not intend to commit plagiarism, such cases will still be treated as plagiarism and punished accordingly.

	Solution: When you write notes from another source always make your notes clear about what the source is and what is a quote or close paraphrase.



The use of direct quotations
:	The use of direct quotations or lightly paraphrased text without citing the source would be deemed to be an assessment offence. Where work was similarly presented, without quotation marks, but with a clear indication of the source this would be identified as bad practice and marked accordingly. In the latter case,
overly-derivative work showing little intellectual input from the student would be likely to be given a low mark, and if extensive the work would be almost certain to fail.

	Solution: If you must quote a source put the quote in quotation marks and reference it correctly both in the body of the essay and in the full reference list. It is however better to synthesise the ideas and put them into your own words. You will still need to reference the source of the ideas.

 

### Preventing academic dishonesty

Everyone involved in higher education is responsible for preventing the incidence of academic dishonesty. Prime responsibility rests with students themselves. You can help reduce the incidence of academic dishonesty through following these points of principle:


Be organised in your work
:	Students committing academic dishonesty often claim that time pressures and last minute panic led them to cheat. Such panic might be a reason for cheating but it does not excuse it. You can reduce the likelihood of such pressures by being organised, knowing what assessment deadlines you have to meet, and planning your work accordingly. If you are not a good organiser, take advice. Advice is available from your personal tutor, from study skills courses run by the University and from your network of friends and colleagues.


Know the rules
:	It is tremendously important to know what counts as
academic dishonesty. One problem is of course that there is no hard and fast cut off between honesty and dishonesty; there are gradations between best practice and utterly dishonest practice. It is essential that you get a sense of where the boundary lies on this gradation. In Stage 1, this topic will be discussed as one of the tutorial topics. There are also exercises available on the student portal which aim to help you understand where this boundary lies. Sometimes students plead that ignorance of the rules led them to cheat. Again this ignorance may be a reason for cheating, but it does not excuse it.


Don’t ignore dishonest practice
:	There are occasions where you suspect a fellow student of committing academic dishonesty. The most common form of this practice occurs where another student uses or copies your work without your permission. If you suspect that someone is cheating in this way, then you can talk to your personal tutor, the relevant marker, the relevant module leader, the stage tutor or programme co-ordinator all in confidence. If your suspicion is well founded then the member of staff will take steps to detect the cheating without involving you directly.


Be aware of detection systems
:	The School of Psychology has systems for checking work submitted for assessments and detecting academic dishonesty. The marker is obviously in a good position to detect cheating such as plagiarism. The School may also ask a randomly selected sample of students to submit electronic copies of their assessment after the deadline has passed. These copies will be subjected to plagiarism detection software which compares the content of essays with that of other student essays and with text on web sites and in journals and books. By being able to match the content of the essay with these different sources, this software now has a very high detection rate for plagiarism.


### Consequences of academic dishonesty

If a marker believes your assessment shows signs of cheating, then the university procedures will be followed.

When the student has been informed by the module
leader that he or she is suspected of an offence under the university regulations, then they will have an opportunity to discuss this charge with the module leader.  The student then has to decide whether to accept the charge or contest it in front of a faculty committee.

If a student is found guilty of academic dishonesty then they will be punished, usually as a minimum by having the grade for the work submitted or the module as a whole reduced to zero.

Every year, a number of students have their marks reduced
and fail the modules concerned. If you have your marks reduced to zero because of academic dishonesty then the impact on your overall mark profile and your eventual degree classification can be high. The information will be kept on your academic file, and may be referred to by your tutor or other member of staff when writing a reference for you after you leave the University. A second offence may lead to removal of the student from their programme of study.
