# Careers

Great careers aren't built overnight. They evolve out of lots of small efforts,
undertaken daily, that eventually grow into the seeds of a satisfying career.
Taking the initiative and planning your career means you are more likely to get
the type of job that you will enjoy.

A key goal of the programme is to help our graduates into professional
employment, and we offer a range of activities and opportunities within the year
to help with this. For administrative conveninence, these are typically
scheduled through the Personal and Professional Development (PSYC750) module.

In addition, the university offers a range of employability and careers
services.

## Plymouth Connect

Final year and masters students are invited to join Plymouth Connect, an
exciting new online platform, connecting you with Plymouth alumni around the
world.

-   acquire top tips from an experienced professional
-   gain an insight into your preferred industry or career
-   build your professional network
-   get help in recognising your own abilities and areas for development
-   gain practical advice on job search techniques and skills
-   develop and improve your employability skills.

Our alumni have years of experience in an array of professions and sectors, and
they want to draw on their knowledge to help you!

To find out more and register please follow the link:
<https://www.plymouth.ac.uk/student-life/your-studies/academic-services/careers-and-employability/plymouth-connect>

## Academic and character references {#academic-references}

Project supervisors and the programme leads will both, normally, be happy to
provide academic and character references for students applying for PhD funding
or jobs.

Please bear in mind that at busy times of year staff may have quite a few
references to write. You can make their job easier, and improve the quality of
reference your recieve, by providing:

-   An up to date copy of your CV

-   Details of what the reference is for, and any salient details of the job
    description or person specficiation you would like your reference to
    highlight/mention.

-   A quick summary of the highlights of your academic performance (e.g. list
    modules with best grades, and note what you found interesting about each)

-   The title, grade, and a quick summary of your undergraduate dissertation if
    you would like this mentioned in the reference (this can be a good idea if
    it relates to the application in question).

-   Non-academic highlights from your time at Plymouth, which you would like
    mentioned.

-   Any other outstanding characteristics or activities it would be helpful to
    note in the reference.

By providing these details you make it the whole process much quicker and it is
more likely that your positive attributes will be accurately remembered and
included in the reference!

Supervisors will often provide you a copy of academic references on request, and
it can be useful to keep this on file because many employers will accept a
generic character reference from-file.

## [Careers Advisory Service](https://www.plymouth.ac.uk/student-life/your-studies/academic-services/careers-and-employability)

The University has an excellent careers service, with specific expertise in
Psychology. Paul Gillard is our point of contact (you will meet Paul during the 
programme) and he is able to offer individual advice session. DO take
advantage of this, even if you have fairly concrete plans for next year - he is
very helpful.

-   <employability@plymouth.ac.uk>
-   01752 587456

## The British Psychological Society

https://careers.bps.org.uk/

This site will tell you all about careers in psychology and courses and
qualifications that will help you get the career you want.

## Higher Education Achievement Report (HEAR)

The HEAR includes and extends the existing record of academic achievement: the
academic transcript, and the European Diploma Supplement. This information
follows the same documentation you would expect for students graduating from any
university in Europe. It also features additional achievements relating to
co-curricular activities which are formally recognised by the University, for
example, the Plymouth Award, being a Student Ambassador or joining up to the
Peer Assisted Learning Scheme (PALS). A full list of what is included on your
HEAR is available on the FAQs website. You can also view an example of a mock
HEAR report.

-   <https://www.plymouth.ac.uk/student-life/your-studies/essential-information/higher-education-achievement-report>

## PGCE's and teaching

Many psychology graduates are under the misguided belief that they cannot enter
teaching because they have not studied a national curriculum subject. This
belief is wrong but there is some additional information that you need to know
in order to take your interest in teaching further. Some PGCE providers require
students to have a degree in a subject related to the national curriculum and
you will need to check with individual providers whether they apply this
condition. You will also need Maths and English GCSE at grade C or above, and
science if you want to teach at Primary level.
