# Our expectations {#expectations}

Studying for a masters course is a big commitment. For you to get the best from
the year we expect you to:

-   [Attend](#attendance)
-   [Contribute (small group teaching only works if all students engage)](#contribute)
-   [Work hard (self-directed study is a crucial part of the course)](#self-study)
-   [Communicate with staff](#communicate-with-us) and
    [check your email every day](#email-expectations)

## Attendance {#attendance}

\index{Attendance}

Most students study for an MSc or MPsych as a full time course, and it places
considerable demands on your time and energies. Nonetheless, _we expect all
students to attend all scheduled classes, and some modules require attendance as
part of their assesment criteria._

We know from experience (and results data) that students who don't attend
perform poorly. We recommend that full time students undertake no more than 8
hours part time work per week while teaching is taking place (between September
and April) and it is essential that part time work does not interfere with your
attendance at lectures.

If there are unavoidable circumstances which mean that you cannot attend the
University you should register these as 'extenuating circumstances'. Please see
the section on [extenuating circumstances](#excircs) below (page
\pageref{excircs}). You should also discuss these circumstances with the
programme coordinator.

###### Recording of sessions

Lecture-style sessions will be recorded and made available on the DLE. Other 
sessions with portions that lend themselves well to being recorded will 
also be made available. By attending the lectures and workshops, you consent to 
being recorded. Note that it will not always be possible or appropriate to make some 
sections of sessions available as recordings (e.g., those with group discussions 
containing sensitive material). Note also that the lecturer who delivers the session is 
responsible for ensuring that the recording is available on the DLE, but it can 
sometimes take several hours or longer to appear if the central server is busy.

###### Attendance monitoring

\index{Attendance monitoring}

The University is currently initiating a policy of monitoring attendance on all
taught undergraduate and postgraduate courses. Details of this will be finalised
during the year, but it is possible that attendance will be monitored in
selected lectures and workshops throughout the year. Your attendance at each 
online lecture may be automatically logged on our attendance monitoring system.

The University also has specific policies on attendance and engagement for
overseas students, and those with Tier 4 visa requirements.^[More information
can be found at <https://goo.gl/779Ywd>.]

## Contributions in class

Many of our courses require active class participation and the use of group work. 
It is vital to the success of the course that students are prepared to participate 
in small group teaching In order to ensure that all students receive the maximum 
benefits from this model of teaching. 

## Communicate with staff {#communicate-with-us}

It is important that you keep staff on the programme informed of your progress 
at all times. If you are unable to attend sessions it is important to email the 
programme lead and module lead. Please also contact the program lead or your tutor 
if you are experiencing any difficulties that may be affecting your studies. The 
sooner we are aware of problems, the more able we are to help. All staff have 
office hours every week where students can drop in without making appointments. 
If you are unable to attend and staff member’s office hours, please email them to 
arrange a meeting at a different time. Staff will usually contact students via 
email so please check your student email account regularly. 

## Self-directed study {#self-study}

In addition to your timetabled classes, you will need to spend a _significant
amount of time reading, doing exercises, \index{Self study} completing
coursework assignments and revising for tests or examinations_. The University
expects a student to spend 100 hours undertaking a 10-credit module. Given that
you will be studying 180 credits (MSc) or 120 credits (MPsych), this equates to 
1800 hours (MSc) or 1200 (MPsych) per year – a substantial proportion of your 
time. You should bear this is mind if you are considering part-time work, and 
ensure this does not impact on your ability to study.

## Other expectation

If you change either your term time address or your normal vacation address
please make sure that you inform the School. Whenever possible please supply
telephone numbers with your addresses. The university has a strict policy of not
releasing students’ addresses to third parties.
