# Module choices {#module-choices}

\index{Choice (modules)} \index{Module choice}

Prior to induction week the faculty administrator will email students with a
list of options, from which they can select. This will also be provided _during_
induction week for any students applying late.

During induction week we run a number of sessions providing more information
about modules, and all students need to confirm their semester-1 options within
1 week.

Confirming module choices is important because it allows us to enrol you on
modules on the university's digital learning environment, which means you will
get access to teaching materials and will receive email and other communications
from the module leader.

### Changing options or modules {#module-changes}

Requests for changes to modules/options will be considered and accommodated
where possible. Please make applications via email to the faculty administrator
within the first two teaching weeks of each term.

Where optional modules do not overlap in the timetable students _are_ permitted
to sit-in on additional classes, with the agreement of the module or programme
lead.

However you should be clear that you can only be enrolled on 180 credits in
total, and will be required to submit CW for those modules you are enrolled on.
Only modules for which you are enrolled will count towards your degree
classification.

Some modules contain multiple sub-options (e.g. PSY561/PSY562). Provided that
space allows, and with the agreement of the option leader, it is permitted for
students to attend more than one session in the first week and request to change
options thereafter (although we cannot guarantee that all requests can be
accommodated).

### Module choices for PT students.

For part-time students, depending on the programme, there may sometimes be
leeway when deciding which modules to take in which year. If so, consideration
should be given to overall workload, and the balance of options across both
years.

This often means taking more credits in year 2 than 1, because PT students will
be allocated a project supervisor and may complete much of the work required for
the project, even though they are not officially enrolled on the project module.

PT students should discuss this with their programme lead, and confirm which
modules they wish to take within 1 week of the start of term.
