# The Programmes

There are 4 taught postgraduate programmes at Plymouth, as well as a
'conversion' MSc for students who have not studies psychology before.

As shown in the table below, students on MSc awards study 180 credits through
the year, whereas students on the MPsych study 120. Programmes are either in
'Advanced Psychology' (AP) or 'Clinical Psychology' (CP).

Students on the AP and CP awards will often share modules. The MSc
Psychology coversion course is linked to the UG programme, and is not linked to
the AP/CP awards.

| Award/Subject       | MSc         | MPsych      |
| ------------------- | ----------- | ----------- |
| Advanced Psychology | 180 credits | 120 credits |
| Clinical Psychology | 180 credits | 120 credits |

##### The MSc Psychology (conversion)

This course is a taught MSc programme, but is designed for students without a
psychology degree who wish to gain BPS accreditation.

The MSc conversion is run separately from the AP/CP awards, and you won't be
taught alongside these students.

For more details on the MSc conversion course see:

-   <https://www.plymouth.ac.uk/courses/postgraduate/msc-psychology>

## Official module and programme documentation {-}

The University keeps an official, publicly available record of all current
modules and programmes which it has validated. The record of a module is called
a Definitive Module Record (DMR) and for a whole programme, it is called a
programme specification. The DMR provides information on the aims, intended
learning outcomes, indicative syllabus content of the module and other relevant
matters. The programme specification provides information on the rationale, aims
and intended learning outcomes of the programme as well as information on the
way the programme is organised. You can find these documents by typing the
module code or the phrase ‘Psychology Programme Specification’ into the search
tab at the top of your portal start page.

Details of the standard University academic regulations can be found at this
link:

https://www.plymouth.ac.uk/your-university/governance/student-handbook

## External validation

Each year external experts visit the school to check our teaching and marking,
and listen to students about their experience on the course.

-   [See more about the role of an external examiner here](https://www.heacademy.ac.uk/knowledge-hub/external-examining)

Our external examiners produce a report of their findings each year, which are
listed below:

-   [2017](ee/2017.pdf)
-   [2016](ee/2016.pdf)
