# Advanced Psychology

### Overview (MSc and MPsych)

Students on the AP awards gain in-depth and highly specialised expertise with
cutting edge theory and methods in their area of interest, using elective
modules to tailor their path through the programme to their chosen specialty,
undertaking novel research, and extending the boundaries of current knowledge
under the guidance of experts.

### Programme lead

Chris Berry TODO add details

## Course aims

###### A thorough, experientially-based training in psychological research methods.

Through core modules in advanced research methods students on all programmes
will gain a secure understanding of the theory, application and limitations of
quantitative statistical methods for experimental and observational data.
Enhanced emphasis will be placed on fluency in data manipulation and
visualisation, and in developing insight and understanding for the ways in which
assumptions and theory form the basis on which statistics can be used for
scientific inference. Specialist techniques (e.g. Bayesian inference, approaches
to causal analysis in non-experimental data) will be offered as options, to
ensure students can extend this conceptual understanding with practical
experience applying specific techniques required in particular research domains.

###### Advanced, training in theoretical and empirical advances in cognitive and brain science, behaviour change, or clinical psychology.

Through the “current issues” and “foundations of clinical psychology” modules
students will develop awareness and understanding of new research questions,
debates and findings in their chosen field. Elective modules will enable
students to extend this knowledge, tailoring their learning according to their
specific interests. These modules are cross-cutting in nature, designed to
integrate multiple research perspectives and prove relevant in different
combinations for a variety of students. For example, modules such as The Brain
and its Disorders enable students to explore in detail current knowledge of
specific conditions, providing a secure grounding in the neuroscience of
clinical approaches to schizophrenia, Parkinson’s disease and dementia.

###### Deep and thorough conceptual understanding of chosen areas of study

All aspects of these programmes aim towards deepening conceptual understanding
of the theoretical, empirical, and methodological advances in their field.
Students’ achievements on each module will be assessed entirely through
coursework, which will provide a stimulus and opportunity for them to critically
evaluate the material covered, to apply it to new problems, and to develop new
ideas for future research.

###### Professionalism and professional identity

For all programmes, we shall organise the academic year such that students are
encouraged to think of psychological research and practice as an iterative,
cyclical process involving: enquiry, design, technique, communication, practice,
and reflection. Students will be encouraged to reflect on their learning
regularly throughout the year, and tutorial activities will ensure this is
integrated within their own research practice. The work undertaken in all
modules aims to develop students’ critical understanding of research
methodology, and apply it to the design of their own research projects.
