# Clinical Psychology

### Overview (MSc and MPsych)

The MSc Clinical Psychology (CP) forms part of four, interlinked programmes at
level 7, which offer advanced training in the methods and application of
psychological science, linked to advanced treatment of the psychological
theories and methods in their chosen area of specialisation.

Students on the MSc CP gain training in foundational methods for psychological
research, forming the basis for a professional career as a clinical psychologist
in their role as scientist practitioner. Students also practice core clinical
skills and develop competencies that will prepare them for demanding clinical
careers, and a highly competitive job market.

### Programme lead

I have been a Lecturer in Psychology at University of Plymouth, School of 
Psychology since 2011. I run the MPsych and MSc Clinical Psychology programmes 
as well as acting as module lead for some of the clinical modules. I also work 
privately as a psychotherapist. My research interests include working with 
people with long term conditions, particularly those with appearance-altering 
conditions and brain injuries. I have experience of working with clients and 
family members of those with acquired brain injuries, both in research and in 
clinical practice. I am also a trustee for Headway Somerset.  

## Course aims

###### Advanced, training in theoretical and empirical advances in clinical psychology.

Through the “current issues” and “foundations of clinical psychology” modules
students will develop awareness and understanding of new research questions,
debates and findings in their chosen field. Elective modules will enable
students to extend this knowledge, tailoring their learning according to their
specific interests. These modules are cross-cutting in nature, designed to
integrate multiple research perspectives and prove relevant in different
combinations for a variety of students. For example, modules such as The Brain
and its Disorders enable students to explore in detail current knowledge of
specific conditions, providing a secure grounding in the neuroscience of
clinical approaches to schizophrenia, Parkinson’s disease and dementia.

###### A thorough, experientially-based training in psychological research methods.

Through core modules in advanced research methods students on all programmes
will gain a secure understanding of the theory, application and limitations of
quantitative statistical methods for experimental and observational data.
Enhanced emphasis will be placed on fluency in data manipulation and
visualisation, and in developing insight and understanding for the ways in which
assumptions and theory form the basis on which statistics can be used for
scientific inference. Specialist techniques (e.g. Bayesian inference, approaches
to causal analysis in non-experimental data) will be offered as options, to
ensure students can extend this conceptual understanding with practical
experience applying specific techniques required in particular research domains.

###### Deep and thorough conceptual understanding of chosen areas of study

All aspects of these programmes aim towards deepening conceptual understanding
of the theoretical, empirical, and methodological advances in their field.
Students’ achievements on each module will be assessed entirely through
coursework, which will provide a stimulus and opportunity for them to critically
evaluate the material covered, to apply it to new problems, and to develop new
ideas for future research.

###### Professionalism and professional identity

For all programmes, we shall organise the academic year such that students are
encouraged to think of psychological research and practice as an iterative,
cyclical process involving: enquiry, design, technique, communication, practice,
and reflection. Students will be encouraged to reflect on their learning
regularly throughout the year, and tutorial activities will ensure this is
integrated within their own research practice. The work undertaken in all
modules aims to develop students’ critical understanding of research
methodology, and apply it to the design of their own research projects.

We will use innovative and engaging techniques to provide practical training in
key clinical skills and competencies. In addition to gaining foundational
knowledge of the relevant clinical guidelines and regulations, students will
learn within an environment which fosters the development of key attributes of
clinicians. Students will be expected to demonstrate the principles of values
based practice and to be governed by professional and regulatory codes of
conduct and ethics. Reflective practice will be fostered through opportunities
to engage in personal and professional development.

Students will work in an environment alongside other clinicians and clinical
traineers, and be exposed to a wide range of clinical professionals, along with
the DClinPsy trainees, who will provide a model for the attributes and qualities
required of learners. Through the school’s position in the faculty of health and
humans sciences, students on the CP awards are encouraged to access a wide range
of events which extend their learning, including research seminars in the health
professions, Schwartz rounds, and other CPD-type events as appropriate to the
students’ stage and interests. Through tutorials and reflective practice
students will be encouraged to engage with personal and professional development
so as to develop an identity as a professional clinical worker. This intensive
approach to developing, reflecting on and documenting clinical competencies
provides may advantages: students can engage with important clinical skills in a
safe environment, with structured and intensive feedback on their performance,
and without the complexities and limitations of trying to develop these clinical
skills in the workplace, alongside the inevitable competing administrative and
financial considerations. Our structured PT routes provide students wishing to
gain clinical experience (e.g. to support a future DClinPsy application) at the
same time as they study — providing flexibility and choice to students.

## Disclosure and Barring Service Checks

The school routinely applies for DBS checks for all CP students, but for more
information on this please contact the
[senior administrator or faculty admin team](#facultyadmin).
