# (PART) Programme-specific information

# MSc

Welcome to Masters study in Psychology. You are now at the ‘Master’s level’ of study, and you will be expected to make the transition from undergraduate to graduate learning. You will be treated accordingly, but you are expected to attend lectures, to be self-motivated and responsible for your own learning. You are expected to be available for applied skills work, project meetings, and other meetings throughout the week. 
A very important activity in which you will engage this year is your project. This is a major piece of work – it counts for a large number of credits towards your overall stage 5 mark. We place a lot of emphasis on getting you to work on the planning, conduct and analysis of your project.
You will find that there are quite a few deadlines for handing in your coursework assessments that might coincide. Timetabling makes this unavoidable. This can be quite stressful if you try to hand them all in at the last minute. Deadlines are the last possible submission time and cannot be changed. You should try to hand in your work before the deadline, and we strongly advise that you schedule your work accordingly to minimise stress.
This section of the handbook contains information relating specifically to the MSc degree programmes (Advanced and Clinical). You will need to refer to it throughout the year. 


### Degree classifications {#msc-classification}

Overall degree classifications, which are shown on your final degree transcript,
are awarded based on the average mark across all modules, as follows:

-   Distinction (>=70%, grades A- to A+)^[The project must also be awarded an A-
    or better]
-   Merit (60-69%, grades B- to B+)
-   Pass (50%-59%, grades C- to C+)
-   Fail (< 50%, grades D+ and below)

### Progression and graduation

All MSc students must complete 180 credits to graduate. All of the university's
standard postgraduate regulations in relation to assessment and progression
apply.

Students on MSc programmes who fail to complete 180 credits _may_ be offered an
alternative exit award (PgDip or PgCert) as outlined in the relevant programme
specification.
