# MPsych

Welcome to MPsych Stage 5. You are now entering the end point of the degree programme. Many students find this the most challenging, but also the most engaging and rewarding year of study.  It is the year in which you have the opportunity to consolidate and apply the academic skills you have developed over the previous years of the degree.

This final year is a unique integrated undergraduate programme that is comprised of taught modules amounting to 70 credits, an Advanced Applied Skills worth 10 credits, and a project worth 40 credits. Continuous assessment is used throughout and there are no formal examinations on this programme. 

Stage 5 is designed to build on your Psychology stages 1, 2, and 4 knowledge by extending your studies to the equivalent of Master’s level, and giving you an advanced understanding of core topics in research methods, and specialised training that is pertinent to your pathway. You will share some modules with postgraduate students who are taking the MSc in Advanced and Clinical Psychology.

You are now at the ‘Master’s level’ of study, and you will be expected to make the transition from undergraduate to graduate learning. You will be treated accordingly, but you are expected to attend lectures, to be self-motivated and responsible for your own learning. You are expected to be available for applied skills work, project meetings, and other meetings throughout the week. 

Your overall degree mark will be calculated using the weights 10%, 20%, 30%, 40%  for stages 1, 2, 4, and 5 (note stage 1 is based on your best 80 credits). It is therefore important that you do your very best on the assessments required for each module during this stage 5 year. It is worth looking back on your Stage 4 experience and thinking about areas in which you performed well and areas, which you think can be improved. Assessment in Stage 5 is only coursework, so if you have had problems with coursework in the past, you should to talk these issues through with your pathway leader. 

A very important activity in which you will engage this year is your project. This is a major piece of work – it counts for a large number of credits towards your overall stage 5 mark. We place a lot of emphasis on getting you to work on the planning, conduct and analysis of your project.

You will find that there are quite a few deadlines for handing in your coursework assessments that might coincide. Timetabling makes this unavoidable. This can be quite stressful if you try to hand them all in at the last minute. Deadlines are the last possible submission time and cannot be changed. You should try to hand in your work before the deadline, and we strongly advise that you schedule your work accordingly to minimise stress.

This section of the handbook contains information relating specifically to the MPsych stage 5 programmes (Advanced and Clinical). You will need to refer to it throughout the year. 


### Degree classifications {#mpsych-classification}

Overall degree classifications, which are shown on your final degree transcript,
are awarded based on the average mark across all modules, as follows:

-   First (>=70%, grades A- to A+)
-   2:1 (60-69%, grades B- to B+)
-   2:2 (50%-59%, grades C- to C+)
-   Fail (< 50%, grades D+ and below)

### Progression and graduation

All MPsych students in their final year (stage 5) must complete 120 credits to
graduate with an MPsych award.

For this final year of the degree, the university' standard postgraduate
regulations in relation to assessment and progression apply.

Students on the MPsych programmes who fail to complete 120 credits in their
final year will be awarded a BSc degree, based on their work in stage 1-4. See
the programme specification for more details, or speak to the [faculty
administrator](#facultyadmin.
