
The primary responsibility for your safety and your health lies with yourself.
The University, Faculty and School publish Safety handbooks which are available online through the portal. These provide guidance on safe working practices and specific risks which you may encounter.

### Fire
In the event of a fire alarm sounding you must leave the building by the nearest available main exit. If your route to a main exit is obstructed then you should evacuate by way of the next available fire exit. When the alarm sounds you must stop what you are doing immediately, even if you are in the middle of an experiment you must stop. If you are a researcher running an experiment then you should make sure that your participant(s) respond to the alarm. Do not use the lifts or re-enter the building until the all clear is given by a fire marshal (wearing a yellow tabbard)

### General Hazards
The responsible safety manager is Professor Tim Hollins, as Head of School. Safety coordination within the School is delegated to the Technical Manager, Anthony Mee. Any concerns about safety should be communicated to Anthony in the Technical Office, Room Link 109. If you become aware of any hazard or broken equipment this should be reported immediately to the Technical Office.

### Health
If you make extensive use of computers you should familiarise yourself with advice available online regarding posture and working position. In general laptops are poorly designed for extensive periods of use and desktop screens should be adjusted to be at eye level. If you suffer from any condition requiring medication or reducing your mobility please make sure that those around are aware and know what to do in the event of an emergency. Security staff are all trained first aiders, and in the Link block Lynne James in the Technical Office is also a First Aider.

### Lone Working
Students are not allowed to remain in the Labs after 5pm unless accompanied by a member of staff. Undergraduates should never work alone with public participants. Personal alarms are available from the Technical Office if required.

